### ISSUE TITLE
Cuphead run 'n' gun flashing 

### ISSUE THREAD

**Issue by Keith94** [masterotaku/fixes-backup#1]
Hi,
The texture replacement mod that comes with your fix doesn't affect the flashing "Run 'n' Gun" text at the beginning of side-scrolling levels. Can you add support for disabling that flashing?
Btw it works fine with the boss levels.

**Comment by masterotaku** [comment]
OK. I'll take a look soon. It should be easy like boss battles. I suppose I forgot to check run & gun levels. I'll update and bump the blog post when it's done and then I'll close this.

**Comment by Keith94** [comment]
Thanks dude!

**Comment by masterotaku** [comment]
Fix updated. Get it on the blog again (I didn't bump the post to the front page). They were two extra textures for the no flashing mod.

**Comment by Keith94** [comment]
Yep, works great now. The line changed from 996 to 1062 (blog description wasn't updated ;)).

**Comment by masterotaku** [comment]
Thanks for that. I didn't remember about updating the line number.
